### ISSUE TITLE
legend_fields_to_hide / getLegendOptions is unable to order enabled fields

### ISSUE THREAD

**Issue by tiedotguy** [signalfx/terraform-provider-signalfx#13]
When there are several fields enabled, the important ones should be pulled to the top of the list so that they appear in chart tooltips without being truncated.

With the current setup, this isn't possible to express in tf, as fields can only be hidden, not ordered.

I would probably implement this as a new resource argument that `getLegendOptions` checks first, but I'm not sure the best name for it. `legend_fields_to_prioritize` maybe?

**Comment by cory-signalfx** [comment]
Hey @tiedotguy! Sorry for the delay, I was on vacation.

Hrmmmm, curious. This is indeed annoying. For future spelunkers, the issue is that the API has a `legendOptions.fields` that contains an array of objects, each is a field name and an `enabled` property that can be true or false.  `legend_fields_to_hide` as it stands only allows you to specify which fields you want to _hide_. This confuses me a bit, since the API states that the only fields shown will be those marked as "true". If fields are not included, why do they show up?

If I were able to have whatever I wanted, I'd probably ask to have a new property that is `ConflictsWith: legend_fields_to_hide`. Then we can remove `legend_fields_to_hide` in 2.0.

Thoughts?

**Comment by tiedotguy** [comment]
All good! As you can probably tell, we're ramping up our adoption and finding all the corner cases :)

That would make more sense, I'm not familiar with the TF model, so didn't realize it was an option.  Definitely cleaner than adding a second flag.

I think the best approach would be to confirm the actual implementation and have it flow from there to documentation, then Terraform.  That ensures we're working off defined behavior rather observed behavior.

**Comment by cory-signalfx** [comment]
Okey doke. I think I'll hold into this until I finish #15 and then maybe take a stab at changing it as I have free time this week. Sound good?

**Comment by tiedotguy** [comment]
Awesome!

**Comment by cory-signalfx** [comment]
Merged and tagging soon!
