### ISSUE TITLE
Dangling dashboard created with dashboard group

### ISSUE THREAD

**Issue by MovieStoreGuy** [signalfx/terraform-provider-signalfx#14]
Creating a dashboard group also creates a default dashboard assigned to it which can't be accessed in terraform to be able to add charts do it. 

This often leaves a dashboard that is blank inside the dashboard group that can't be configured with terraform.

**Comment by sm4** [comment]
Example terraform template:
```
resource "signalfx_dashboard_group" "example" {
  name = "Example"
  description = "This will have an empty dashboard called 'Example'"
}
```
Creating a dashboard called 'Example' inside the group creates a new dashboard with the same name, resulting in two dashboards called 'Example' inside the group.

**Comment by cory-signalfx** [comment]
Hey there! Sorry for the slow response, I was on vacation!

This is actually a property of the SignalFx API. If a [Dashboard Group is created](https://developers.signalfx.com/dashboard_groups_reference.html#tag/Create-Single-Dashboard-Group) via the API and specifies no dashboards, then one is created for it. I suspect this is because the SignalFx web app has no concept of viewing a dashboard group that has no dashboards. Unfortunately it also works in the *other* direction. [Creating a dashboard](https://developers.signalfx.com/dashboards_reference.html#operation/Create%20Single%20Dashboard) with no group creates an implicit dashboard group. Ugh!

This puts us in a bit of a chicken and egg problem. As it stands a `signalfx_dashboard_group` does not allow us to specify dashboards. Instead a `signalfx_dashboard` is required to specify a `dashboard_group`. This requires us to create an empty dashboard group, hence the lame empty dashboard that is made by the API. Even if we switch it, we'll end up with the same problem.

I'll ask around inside and see if I can figure out a way to make this do what I want. Some quick API tests show that there's no easy way out of it. 😄

**Comment by MovieStoreGuy** [comment]
Thank you so much @cory-signalfx

**Comment by cory-signalfx** [comment]
Merged and tagging in a moment!
