### ISSUE TITLE
Support for Terraform 0.12.00

### ISSUE THREAD

**Issue by MovieStoreGuy** [signalfx/terraform-provider-signalfx#29]
Hi team,

I have had a quick glance over the changes for 11.x to 12.x and it looks to be a lot of changes required within the provider to make it happen.

This feels like an epic within its own right but I wanted to open it to have some way to track progress and what needs to happen.

**Comment by cory-signalfx** [comment]
Roger! I planned on doing a spike/investigation of this during this week. I'll keep this here as a way of tracking that word. :)

**Comment by MovieStoreGuy** [comment]
Looking at the PR, do you know if that will continue to work with versions  0.11.x?

**Comment by cory-signalfx** [comment]
You have to publish a binary for each. There are no code changes required otherwise, so this will just be a matter of publishing both as branches until dropping 0.11. I'll be asking Hashicorp about this soon.

**Comment by MovieStoreGuy** [comment]
Interesting, I should be able to use it within our bundled releases just need something to go off, either a tag or a branch.

**Comment by cory-signalfx** [comment]
The branch is #32 or `cory-tf-0-12`. I see some older comments about adding a version number to provider binaries so that things like this can coexist with terraform versions, but I am unsure if that still works or if you can use [aliasing](https://www.terraform.io/docs/configuration/providers.html#alias-multiple-provider-instances).

Regardless, I have no plans to make 0.11 or 0.12 differ in any meaningful way for the time being. 0.11 will need to keep existing for a bit.

**Comment by cory-signalfx** [comment]
Hey @MovieStoreGuy! Just flagging this `master` is now 0.12!
