### ISSUE TITLE
Some dashboard never show up

### ISSUE THREAD

**Issue by detouched** [signalfx/terraform-provider-signalfx#58]
I have a setup that manages two dashboard groups with 13 dashboards in each. 

When I deploy them from scratch it often happens that some of the dashboards don't appear in SignalFX. Output of `terraform apply` is ok (I can find those missing dashboards reported as created).
I can't find any pattern here: it's always a random dashboard(s) that is/are missing. It looks like this only happens when many objects are being created, e.g. when there're many dashboards

Can this be caused by the adapter or is it an issue with SignalFX itself? Some connections not being closed on dashboard-to-group linking request maybe?

**Comment by cory-signalfx** [comment]
I think this is a situation where the SignalFx API is saying it's done with an operation, but it is in fact not done. The API reports a 200 but some of the data may not have been saved yet, so subsequent operations may race.

We're working internally on some improvements that should mitigate this. For now I have no fixes. :(

**Comment by cory-signalfx** [comment]
@detouched If you encounter this again, can use [terraform state show](https://www.terraform.io/docs/commands/state/show.html) to find the ID of the dashboard in question and try to browse to it in the UI?

There's some speculation that we're racing somewhere, but since the relationship is "create group, dashboard contains reference to group id" I don't really grok how that can happen without violating causality. If you can help me verify we can likely improve the data we have.

**Comment by cory-signalfx** [comment]
Hey @detouched! As of this week we're hoping that some improvements we've made will decrease the likelihood of this occurring. Since it's not rooted in the Terraform provider I'm going to chose this, but please worth with our support team if you see it reoccur so we can focus our efforts. ❤️
